version: 2

models:
  - name: SILVER_ACRES_HARVESTED
    description: "Cleaned, analysis-ready table of acres harvested by county, commodity, and year. Columns are selected and renamed for downstream analysis and joining."
    columns:
      - name: YEAR
        description: "Year the data was collected."
        tests:
          - not_null
      - name: COUNTY_NAME
        description: "Name of the county where the data was collected."
        tests:
          - not_null
      - name: COUNTY_CODE
        description: "Numeric code for the county."
        tests:
          - not_null
      - name: STATE_NAME
        description: "Name of the state where the data was collected."
        tests:
          - not_null
      - name: STATE_ALPHA
        description: "Two-letter state abbreviation (e.g., TN)."
        tests:
          - not_null
      - name: STATE_FIPS_CODE
        description: "FIPS code for the state."
        tests:
          - not_null
      - name: COMMODITY_DESC
        description: "Description of the commodity (e.g., CORN)."
        tests:
          - not_null
      - name: ACRES_HARVESTED
        description: "Number of acres harvested, renamed from VALUE."
        tests:
          - not_null
      - name: UNIT_DESC
        description: "Unit of measurement for the value (e.g., ACRES)."
        tests:
          - not_null
      - name: STATISTICCAT_DESC
        description: "Description of the statistical category (e.g., AREA HARVESTED)."
        tests:
          - not_null

  - name: SILVER_FIELD_YIELDS
    description: "Cleaned, analysis-ready table of field yields by county, commodity, and year. Columns are selected and renamed for downstream analysis and joining."
    columns:
      - name: YEAR
        description: "Year the data was collected."
        tests:
          - not_null
      - name: COUNTY_NAME
        description: "Name of the county where the data was collected."
        tests:
          - not_null
      - name: COUNTY_CODE
        description: "Numeric code for the county."
        tests:
          - not_null
      - name: STATE_NAME
        description: "Name of the state where the data was collected."
        tests:
          - not_null
      - name: STATE_ALPHA
        description: "Two-letter state abbreviation (e.g., TN)."
        tests:
          - not_null
      - name: STATE_FIPS_CODE
        description: "FIPS code for the state."
        tests:
          - not_null
      - name: COMMODITY_DESC
        description: "Description of the commodity (e.g., CORN)."
        tests:
          - not_null
      - name: YIELD
        description: "Yield per acre, renamed from VALUE. Units vary by crop."
        tests:
          - not_null
      - name: UNIT_DESC
        description: "Unit of measurement for the yield (e.g., BUSHELS/ACRE, TONS/ACRE)."
        tests:
          - not_null
      - name: STATISTICCAT_DESC
        description: "Description of the statistical category (e.g., YIELD)."
        tests:
          - not_null

  - name: SILVER_PRODUCTION
    description: "Cleaned, analysis-ready table of crop production by county, commodity, and year. Columns are selected and renamed for downstream analysis and joining."
    columns:
      - name: YEAR
        description: "Year the data was collected."
        tests:
          - not_null
      - name: COUNTY_NAME
        description: "Name of the county where the data was collected."
        tests:
          - not_null
      - name: COUNTY_CODE
        description: "Numeric code for the county."
        tests:
          - not_null
      - name: STATE_NAME
        description: "Name of the state where the data was collected."
        tests:
          - not_null
      - name: STATE_ALPHA
        description: "Two-letter state abbreviation (e.g., TN)."
        tests:
          - not_null
      - name: STATE_FIPS_CODE
        description: "FIPS code for the state."
        tests:
          - not_null
      - name: COMMODITY_DESC
        description: "Description of the commodity (e.g., CORN)."
        tests:
          - not_null
      - name: PRODUCTION
        description: "Total crop production, renamed from VALUE. Units vary by crop."
        tests:
          - not_null
      - name: UNIT_DESC
        description: "Unit of measurement for the production (e.g., BUSHELS, TONS)."
        tests:
          - not_null
      - name: STATISTICCAT_DESC
        description: "Description of the statistical category (e.g., PRODUCTION)."
        tests:
          - not_null
  - name: SILVER_WEATHER_OPEN_METEO
    description: "Cleaned, analysis-ready table of daily weather metrics by location. Columns are selected and parsed for downstream analysis and joining."
    columns:
      - name: LATITUDE
        description: "Latitude of the weather data location."
        tests:
          - not_null
      - name: LONGITUDE
        description: "Longitude of the weather data location."
        tests:
          - not_null
      - name: TIMEZONE
        description: "Timezone of the weather data location (e.g., America/Chicago)."
        tests:
          - not_null
      - name: DAY_NUMBER
        description: "The day index in the array (1-based)."
        tests:
          - not_null
      - name: VALUE
        description: "The daily weather value (temperature or precipitation, depending on DAILY_UNITS)."
        tests:
          - not_null
      - name: DAILY_UNITS
        description: "The unit of measurement (e.g., '°C' for temperature, 'mm' for precipitation)."
        tests:
          - not_null
      - name: LOAD_TIMESTAMP_UTC
        description: "Timestamp (UTC) when the data was loaded into Snowflake."
        tests:
          - not_null
  - name: SILVER_TENNESSEE_COUNTY_CROP_PRODUCTION_2022
    description: "Cleaned, analysis-ready table of Tennessee county crop production for 2022. Columns are selected and renamed for downstream analysis and joining."
    columns:
      - name: YEAR
        description: "Year the data was collected."
        tests:
          - not_null
      - name: STATE
        description: "Name of the state."
        tests:
          - not_null
      - name: STATE_ANSI
        description: "ANSI code for the state."
        tests:
          - not_null
      - name: COUNTY
        description: "Name of the county."
        tests:
          - not_null
      - name: COUNTY_ANSI
        description: "ANSI code for the county."
        tests:
          - not_null
      - name: COMMODITY
        description: "Name of the commodity."
        tests:
          - not_null
      - name: DATA_ITEM
        description: "Type of data item (e.g., YIELD, PRODUCTION)."
        tests:
          - not_null
      - name: VALUE
        description: "Value for the data item."
        tests:
          - not_null
      - name: CV_PERCENT
        description: "Coefficient of variation percent."
        tests:
          - not_null
      - name: LOAD_TIMESTAMP_UTC
        description: "Timestamp (UTC) when the data was loaded into Snowflake."
        tests:
          - not_null
  

