version: 2

models:
  - name: SILVER_ACRES_HARVESTED
    description: "Cleaned, analysis-ready table of acres harvested by county, commodity, and year. Columns are selected and renamed for downstream analysis and joining."
    columns:
      - name: YEAR
        description: "Year the data was collected."
      - name: COUNTY_NAME
        description: "Name of the county where the data was collected."
      - name: COUNTY_CODE
        description: "Numeric code for the county."
      - name: STATE_NAME
        description: "Name of the state where the data was collected."
      - name: STATE_ALPHA
        description: "Two-letter state abbreviation (e.g., TN)."
      - name: STATE_FIPS_CODE
        description: "FIPS code for the state."
      - name: COMMODITY_DESC
        description: "Description of the commodity (e.g., CORN)."
      - name: ACRES_HARVESTED
        description: "Number of acres harvested, renamed from VALUE."
      - name: UNIT_DESC
        description: "Unit of measurement for the value (e.g., ACRES)."
      - name: STATISTICCAT_DESC
        description: "Description of the statistical category (e.g., AREA HARVESTED)."

  - name: SILVER_FIELD_YIELDS
    description: "Cleaned, analysis-ready table of field yields by county, commodity, and year. Columns are selected and renamed for downstream analysis and joining."
    columns:
      - name: YEAR
        description: "Year the data was collected."
      - name: COUNTY_NAME
        description: "Name of the county where the data was collected."
      - name: COUNTY_CODE
        description: "Numeric code for the county."
      - name: STATE_NAME
        description: "Name of the state where the data was collected."
      - name: STATE_ALPHA
        description: "Two-letter state abbreviation (e.g., TN)."
      - name: STATE_FIPS_CODE
        description: "FIPS code for the state."
      - name: COMMODITY_DESC
        description: "Description of the commodity (e.g., CORN)."
      - name: YIELD
        description: "Yield per acre, renamed from VALUE. Units vary by crop."
      - name: UNIT_DESC
        description: "Unit of measurement for the yield (e.g., BUSHELS/ACRE, TONS/ACRE)."
      - name: STATISTICCAT_DESC
        description: "Description of the statistical category (e.g., YIELD)."

  - name: SILVER_PRODUCTION
    description: "Cleaned, analysis-ready table of crop production by county, commodity, and year. Columns are selected and renamed for downstream analysis and joining."
    columns:
      - name: YEAR
        description: "Year the data was collected."
      - name: COUNTY_NAME
        description: "Name of the county where the data was collected."
      - name: COUNTY_CODE
        description: "Numeric code for the county."
      - name: STATE_NAME
        description: "Name of the state where the data was collected."
      - name: STATE_ALPHA
        description: "Two-letter state abbreviation (e.g., TN)."
      - name: STATE_FIPS_CODE
        description: "FIPS code for the state."
      - name: COMMODITY_DESC
        description: "Description of the commodity (e.g., CORN)."
      - name: PRODUCTION
        description: "Total crop production, renamed from VALUE. Units vary by crop."
      - name: UNIT_DESC
        description: "Unit of measurement for the production (e.g., BUSHELS, TONS)."
      - name: STATISTICCAT_DESC
        description: "Description of the statistical category (e.g., PRODUCTION)."
  - name: SILVER_WEATHER_OPEN_METEO
    description: "Cleaned, analysis-ready table of daily weather metrics by location. Columns are selected and parsed for downstream analysis and joining."
    columns:
      - name: LATITUDE
        description: "Latitude of the weather data location."
      - name: LONGITUDE
        description: "Longitude of the weather data location."
      - name: TIMEZONE
        description: "Timezone of the weather data location (e.g., America/Chicago)."
      - name: DATE
        description: "Date for the weather observation."
      - name: TEMPERATURE
        description: "Daily temperature value (units depend on source, e.g., °C)."
      - name: PRECIPITATION
        description: "Daily precipitation value (units depend on source, e.g., mm)."
      - name: LOAD_TIMESTAMP_UTC
        description: "Timestamp (UTC) when the data was loaded into Snowflake."
